### ISSUE TITLE
Wireframes and basic design meeting at 9am/12pm

### ISSUE THREAD

**Issue by stepheff1994** [Siphon880gh/your-daily-portal-adaigo-element#1]
Choosing design planning it out
Having exactly the number of steps the user will need to take to reach the end result

**Comment by RobertWilliamCampagna** [comment]
Hey Stephanie and Weng!  Here are some wireframes for the project.  Its a simple basic layout, we can add after you two review.  I zipped the files, let me know if this doesn't work and I will take screen shots and send them.
[ZenPage.bmpr.zip](https://github.com/Siphon880gh/ucla-collab-related-artists/files/5563400/ZenPage.bmpr.zip)

**Comment by RobertWilliamCampagna** [comment]
Ok, sorry about that.  Lets see if this works.

<img width="1792" alt="Screen Shot 2020-11-18 at 6 01 52 PM" src="https://user-images.githubusercontent.com/71302867/99611456-8ebed080-29c8-11eb-9d3c-bf153bf19392.png">
<img width="1792" alt="Screen Shot 2020-11-18 at 6 01 56 PM" src="https://user-images.githubusercontent.com/71302867/99611473-97170b80-29c8-11eb-84b5-c227d8497f71.png">
<img width="1792" alt="Screen Shot 2020-11-18 at 6 02 46 PM" src="https://user-images.githubusercontent.com/71302867/99611486-9da58300-29c8-11eb-968a-39cf5469edbf.png">
<img width="1792" alt="Screen Shot 2020-11-18 at 6 02 57 PM" src="https://user-images.githubusercontent.com/71302867/99611491-a0a07380-29c8-11eb-805b-6919e0774c61.png">
<img width="1792" alt="Screen Shot 2020-11-18 at 6 03 50 PM" src="https://user-images.githubusercontent.com/71302867/99611497-a39b6400-29c8-11eb-855d-15c9d07859ad.png">

**Comment by Siphon880gh** [comment]
Well done!
